"""create auth tables

Revision ID: 90a82456a4f1
Revises:
Create Date: 2026-08-12 12:09:12.920875

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90a82456a4f1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False, comment="机构唯一代码"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="机构名称"),
        sa.Column(
            "status",
            sa.Enum("enabled", "disabled", name="organizationstatus", native_enum=False, length=32),
            server_default="enabled",
            nullable=False,
            comment="机构状态",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "siwe_nonces",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nonce", sa.String(length=32), nullable=False, comment="SIWE消息中的随机nonce"),
        sa.Column("wallet_address", sa.String(length=42), nullable=False),
        sa.Column("chain_id", sa.BigInteger(), nullable=False, comment="EIP-155 Chain ID"),
        sa.Column("issued_at", sa.BigInteger(), nullable=False, comment="签发时间，Unix秒级时间戳"),
        sa.Column(
            "expires_at", sa.BigInteger(), nullable=False, comment="过期时间，Unix秒级时间戳"
        ),
        sa.Column(
            "used",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
            comment="nonce是否已经被消费",
        ),
        sa.Column("used_at", sa.BigInteger(), nullable=True, comment="消费时间，Unix秒级时间戳"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nonce"),
    )
    op.create_index(op.f("ix_siwe_nonces_expires_at"), "siwe_nonces", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_siwe_nonces_wallet_address"), "siwe_nonces", ["wallet_address"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False, comment="用户显示名称"),
        sa.Column("wallet_address", sa.String(length=42), nullable=False),
        sa.Column(
            "role",
            sa.String(length=32),
            server_default="operator",
            nullable=False,
            comment="用户角色",
        ),
        sa.Column("organization_id", sa.BigInteger(), nullable=False, comment="用户所属机构ID"),
        sa.Column(
            "status",
            sa.Enum("enabled", "disabled", name="userstatus", native_enum=False, length=32),
            server_default="enabled",
            nullable=False,
            comment="用户状态",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_address"),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_siwe_nonces_wallet_address"), table_name="siwe_nonces")
    op.drop_index(op.f("ix_siwe_nonces_expires_at"), table_name="siwe_nonces")
    op.drop_table("siwe_nonces")
    op.drop_table("organizations")
    # ### end Alembic commands ###
