name: Ruff Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions: write-all

jobs:
  lint:
    name: Ruff Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff
        id: ruff
        run: uv run ruff check

      - name: Comment PR to notify
        if: always()
        uses: actions/github-script@v9
        with:
          script: |
            const result = '${{steps.ruff.outcome}}';
            let body = '';
            if (result === 'success') {
              body = `🎉🎉🎉 Ruff check passed!
                
              You can go to [Actions](https://github.com/nettedx/nettedx-back/actions) to check the workflow status. ✨`
            } else {
              body = `🚨🚨🚨 Ruff check was failed!

              Please go to [Actions](https://github.com/nettedx/nettedx-back/actions), and check the logs to see what went wrong. 🛠️`
            }
            await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });